### ISSUE TITLE
Detail view error: StudyCourse::getCategories() is null

### ISSUE THREAD

**Issue by vmandal** [in2code-de/in2studyfinder#13]
The detail view gives the following error:

`Return value of In2code\In2studyfinder\Domain\Model\StudyCourse::getCategories() must be an instance of TYPO3\CMS\Extbase\Persistence\ObjectStorage, null returned`

I have enabled the "Enable Typo3 Categorisation for courses" in extension settings.
But the category field is not showing up in the BE for StudyCourse. 

Update:
I disabled "Enable the Caching functionality" in  extension settings
After cache clear etc the error "StudyCourse::getCategories() is null" went way but I still do not see category field for StudyCourse record in BE

TYPO3 11.5.9
PHP version: 7.4.19
in2studyfinder: 8.0.1

**Comment by sebastianstein** [comment]
Thank you for pointing this out. 
This problem is fixed with version 8.0.2.

kind regards
Sebastian Stein
