### ISSUE TITLE
Error when using caching functionality

### ISSUE THREAD

**Issue by klodeckl** [in2code-de/in2studyfinder#14]
Hello, when I activate the caching functionality in the extension settings I get the following error:
Serialization of 'Closure' is not allowed

in2studyfinder 7.3.0
TYPO3 10.4.31
PHP 7.4

Maybe this is related to https://forge.typo3.org/issues/91364?

**Comment by sebastianstein** [comment]
Hello, 

unfortunately, i could not reproduce the described problem. 
Would you have a more detailed description of when the error occurs? 

Does the problem still occur in the newer in2studyfinder versions (V8 or V9)?

Have the existing models of the in2studyfinder been extended? 

Greetings Sebastian

**Comment by klodeckl** [comment]
It seems that the error is gone with in2studyfinder 9.0.1 and TYPO3 11.5.9.
