### ISSUE TITLE
Studyfinder user issue TUM

### ISSUE THREAD

**Issue by franziskahuebner** [in2code-de/in2studyfinder#4]
As a User I noticed a slight problem with the studyfinder of TUM. As I clicked myself through the pages i saw that the page does not automatically scroll up to the beginnig. It would be great if that issue can be fixed.

**Comment by sbusemann** [comment]
It is meant on this url: https://www.tum.de/studium/studienangebot/#

While using the page browser, i get not redirect to the top of the page, if I try to switch to the next page.

**Comment by sebastianstein** [comment]
This is possible by using JavaScript events since version 9.0:

https://github.com/in2code-de/in2studyfinder#javascript-events
