### ISSUE TITLE
Some notes on caching

### ISSUE THREAD

**Issue by fnagel** [in2code-de/in2studyfinder#5]
Something you might want to document somewhere: when using the caching feature, a cache entry could be around 8M pretty quickly. The default `max_allowed_packet` value for MySQL 5.7 is 4M. For earlier versions it's even smaller.

We do not use the listAction / filterAction at all (own controller using Solr), but ran into this issue anyway. Seems the caching of the filters is even processed for the detailAction. Is that needed? Might be reasonable to move the caching away from the initializeAction.

Please close this ticket anytime, I just wanted to make this issue searchable.

**Comment by sebastianstein** [comment]
This problem should be solved with the rework of the course controller in version 8.0.0.
